# vim: set ts=2 sts=2 sw=2 expandtab:
langauge: python
python:
  - "2.6"
  - "2.7"

install:
  - "sudo -H pip install ."
  - "sudo -H pip install -e '.[dev]'"
  - "python2 setup_pynsotrc.py"

script:
  - "py.test tests"
  - "py.test --flake8 -v"

virtualenv:
  system_site_packages: false
